### ISSUE TITLE
Downloading Genshin Impact fails with error

### ISSUE THREAD

**Issue by seriaati** [neon-nyan/Collapse#161] opened 2023-06-06 02:00 UTC
I am on pre-release channel.
Version: 1.70.4 Preview

# GIF
https://iili.io/H4z1BEu.gif

# Error log
```
System.UriFormatException: Invalid URI: The URI is empty.
   at System.Uri.CreateThis(String, Boolean, UriKind, UriCreationOptions& )
   at System.Uri..ctor(String uriString)
   at Hi3Helper.Http.Http.GetContentLengthAsync(String Input, CancellationToken token) in E:\myGit\Collapse\Hi3Helper.Http\Class\Session\SessionManager.cs:line 352
   at Hi3Helper.Http.Http.TryGetContentLengthAsync(String URL, CancellationToken Token) in E:\myGit\Collapse\Hi3Helper.Http\Class\Session\SessionManager.cs:line 336
   at CollapseLauncher.InstallManager.Base.InstallManagerBase`1.TryGetPackageRemoteSize(GameInstallPackage asset, CancellationToken token) in E:\myGit\Collapse\CollapseLauncher\Classes\InstallManagement\BaseClass\InstallManagerBase.cs:line 795
   at CollapseLauncher.InstallManager.Base.InstallManagerBase`1.GetPackagesRemoteSize(List`1 packageList, CancellationToken token) in E:\myGit\Collapse\CollapseLauncher\Classes\InstallManagement\BaseClass\InstallManagerBase.cs:line 788
   at CollapseLauncher.InstallManager.Base.InstallManagerBase`1.StartPackageDownload(Boolean skipDialog) in E:\myGit\Collapse\CollapseLauncher\Classes\InstallManagement\BaseClass\InstallManagerBase.cs:line 127
   at CollapseLauncher.Pages.HomePage.InstallGameDialog(Object sender, RoutedEventArgs e) in E:\myGit\Collapse\CollapseLauncher\XAMLs\MainApp\Pages\HomePage.xaml.cs:line 487
```

**Comment by bagusnl** [comment] 2023-06-06 04:26
Duplicate of #148 
An update is recently pushed to pre and stable regarding this bug, please update and try again

**Comment by neon-nyan** [comment] 2023-06-06 05:03
Hi @seriaati,

As bagus already said above, please update your launcher to the latest version and since the issue should've been fixed now, we are going to close this issue in 24 hours.
Please let us know if you have any issues.

**Closed** 2023-06-06 05:23 UTC
Labels: Bug, Fixed, Game: Genshin Impact, Area: Mirror/API Server
