### ISSUE TITLE
[Bug] Game Resolution in Launcher Game Settings Overriden by GENERAL_DATA_V2_ScreenSettingData_h1916288658 Registry

### ISSUE THREAD

**Issue by bagusnl** [neon-nyan/Collapse#72] opened 2023-01-03 02:54 UTC
With how Collapse do startup arguments for the resolution change. It still get overriden by the registry value on ScreenSettingData. 
I had mine set to 1600x900 in game while in Collapse set to 1920x1080. The game first launched at 1080p (as set by launch arguments by Collapse), then after the Hoyoverse logo appeared, the game will set to 900p as set by registry. This also applies to the Fullscreen setting.

This is the registry output of mine:
```
{"width":1600,"height":900,"isfullScreen":false}
```
While this is the Collapse Game Settings page looks like:
![image](https://user-images.githubusercontent.com/28079733/210294416-9c36f339-cb01-45dd-b196-a191f95f9f77.png)

While at it, can we have a shortcut to the full "Game settings" in the main "Game settings" button that currently only gives some quick settings? My one brain cells sometime just falsely assume these are the same settings even after using this launcher for quite a long time 
![image](https://user-images.githubusercontent.com/28079733/210294618-b7d54d52-52e1-4ed4-aee2-eb30156db8e5.png)

**Comment by Cryotechnic** [comment] 2023-01-03 06:22
> With how Collapse do startup arguments for the resolution change. It still get overriden by the registry value on ScreenSettingData. I had mine set to 1600x900 in game while in Collapse set to 1920x1080. The game first launched at 1080p (as set by launch arguments by Collapse), then after the Hoyoverse logo appeared, the game will set to 900p as set by registry. This also applies to the Fullscreen setting.
> 
> This is the registry output of mine:
> 
> ```
> {"width":1600,"height":900,"isfullScreen":false}
> ```
> 
> While this is the Collapse Game Settings page looks like: ![image](https://user-images.githubusercontent.com/28079733/210294416-9c36f339-cb01-45dd-b196-a191f95f9f77.png)
> 

The typical update process for settings works when you click "Apply Settings". By doing so, Collapse automatically updates the Windows Registry entries with the newly set values. That being said, what seems to be the issue in this case is that Collapse did not write to the specified registry key. The cause can be one of two (2) things:

1. Collapse does not have permissions to access the Windows Registry
2. The user manually updated the values, which causes Collapse to not load the correct registry values. 

`#2` can be remedied in a future patch, but is not the main cause of this issue as the value was never set to `1920x1080` by Collapse.
`#1` on the other hand, depends solely on if the user is running Collapse as an administrator. If it is not, the application will still work, but many of its core features will not. This is why, in an upcoming update, administrator access will be made mandatory (as per #67 & #68).

To eliminate any other causes, can you please post your `settings.ini` as well as `config.ini`? They should both be present in your game's installation folder (e.g. `C:\Games\Hi3Global\settings.ini`). 

@neon-nyan, what're your thoughts on this?

**Comment by bagusnl** [comment] 2023-01-03 06:53
My bad for not testing this earlier with "Apply settings" in Collapse. It does work correctly after doing so. Feel free to close the issue if said behavior is what its intended to be.

But, IMO it would be beneficial for Collapse to recheck the Registry for those everytime it launches (or change region) for the start up argument (Collapse does force `-screen-height` and `-screen-width` argument at launch) that causes the first screen to be at that argument resolution and then switches back to the registry value set in game.

config.ini
```
[General]
channel=1
cps=
game_version=6.2.0
sub_channel=1
sdk_version=
```

settings.ini
```
[SettingsV2]
Fullscreen=True
ScreenResolution=1920x1080
FullscreenExclusive=False
CustomScreenResolution=False
GameGraphicsAPI=3
ResolutionQuality=0
ShadowLevel=1
TargetFrameRateForInLevel=75
TargetFrameRateForOthers=75
ReflectionQuality=0
UseDynamicBone=True
UseFXAA=True
GlobalIllumination=False
AmbientOcclusion=0
VolumetricLight=1
UsePostFX=True
HighQualityPostFX=False
UseHDR=False
UseDistortion=False
BGMVolume=1
SoundEffectVolume=1
VoiceVolume=1
ElfVolume=1
CGVolume=1
CVLanguage=1
LodGrade=0
CustomArgs=
LodLevel=1
```

**Comment by neon-nyan** [comment] 2023-01-08 07:49
> To eliminate any other causes, can you please post your `settings.ini` as well as `config.ini`? They should both be present in your game's installation folder (e.g. `C:\Games\Hi3Global\settings.ini`).
> 
> @neon-nyan, what're your thoughts on this?

Sorry for my very late response on this since I'm just finished my RL activities.
I don't think putting the settings into two types of medium is a good idea since the settings will not be consistent between the one from registry and ``settings.ini`` once the settings from in-game has changed. My suggestion is to get rid all of the parameters inside of the settings.ini and instead directly read/write the values from the registry itself.

**Comment by Cryotechnic** [comment] 2023-01-15 07:15
> > To eliminate any other causes, can you please post your `settings.ini` as well as `config.ini`? They should both be present in your game's installation folder (e.g. `C:\Games\Hi3Global\settings.ini`).
> > @neon-nyan, what're your thoughts on this?
> 
> Sorry for my very late response on this since I'm just finished my RL activities. I don't think putting the settings into two types of medium is a good idea since the settings will not be consistent between the one from registry and `settings.ini` once the settings from in-game has changed. My suggestion is to get rid all of the parameters inside of the settings.ini and instead directly read/write the values from the registry itself.

Was `settings.ini` generated by the launcher? Would need to check if it is still referenced in the code but we could probably migrate to only checking registry instead of adding unnecessary files to the game install folder.

**Comment by neon-nyan** [comment] 2023-01-16 05:47
> Was settings.ini generated by the launcher? Would need to check if it is still referenced in the code but we could probably migrate to only checking registry instead of adding unnecessary files to the game install folder.

Yes, it was automatically generated by the launcher and it applies to both Genshin and Honkai. I would agree to migrate all the references to registry only so there would be no conflict between values.

Also, I just noticed that miHoYo changed the value range for Sound Volume related stuffs from 0 - 3 to 0 - 100 in v6.3. This might need to be changed as well.

**Comment by neon-nyan** [comment] 2023-03-05 11:52
Closing this issue for now as the implementation has been applied in current preview release and also be shipped in the next stable release

**Closed by neon-nyan** 2023-03-05 11:52 UTC
Labels: Enhancement, Area: Preset Config, Game: Honkai Impact 3rd
