### ISSUE TITLE
原神无法更新

### ISSUE THREAD

**Issue by dfmjndm** [neon-nyan/Collapse#85] opened 2023-02-26 14:59 UTC
System.ArgumentNullException: Value cannot be null. (Parameter 'format')
   at System.ArgumentNullException.Throw(String paramName)
   at System.String.FormatHelper(IFormatProvider provider, String format, ReadOnlySpan`1 args)
   at System.String.Format(String format, Object arg0, Object arg1, Object arg2)
   at Hi3Helper.Data.GenshinDispatchHelper..ctor(Int32 RegionID, String DispatchKey, String DispatchURLPrefix, String VersionString, CancellationToken cancelToken) in C:\myGit\Collapse-Legacy\Hi3Helper.Core\Classes\Data\Tools\GenshinDispatchHelper\GenshinDispatchHelper.cs:line 32
   at CollapseLauncher.InstallManagement.InitializeNewGenshinDispatch() in C:\myGit\Collapse-Legacy\CollapseLauncher\Classes\InstallManagement\InstallManagement.cs:line 801

**Comment by neon-nyan** [comment] 2023-02-26 16:57
Hi there,
have you tried to remove the metadata file and re-run the launcher?
Can can you tell me what version do you use right now?

**Comment by dfmjndm** [comment] 2023-02-28 15:59
![image](https://user-images.githubusercontent.com/57401901/221907876-2dcb4b0a-293b-447f-a3d1-a7084ac9d1e8.png)
This is the software version I use. I downloaded the Chinese Mainland version of the game through the official channel. When running the launcher, I was prompted whether to migrate data. I chose Yes. The above content appears after data download and decompression

**Comment by neon-nyan** [comment] 2023-03-01 05:29
I think I know the problem is.
The support for Mainland China's Genshin is kind of buggy so you might experience a problem. This was caused by an empty dispatcher key that being used to connect the launcher into the Game server and due to lack of access into Mainland China's Genshin account, we don't have a way to get the dispatcher key.

And as the lack of support for Mainland China's Genshin for this launcher, I will mark this issue as "help wanted" to hope that someone could help us on getting the dispatcher key.

**Comment by neon-nyan** [comment] 2023-03-01 15:32
Hi there,

This issue will be fixed in the next stable version. But unfortunately, it will not come very soon.
As a fix for this, we have added an ability to Collapse Launcher to skip the verification process after installation in Mainland China's Genshin.

If you want to try out, please use the latest preview release here:
https://github.com/neon-nyan/Collapse/releases/tag/CL-v1.0.69.4-pre

**Closed** 2023-03-01 15:33 UTC
Labels: Help Wanted, Game: Genshin Impact, Need Further Investigation/Attention, Area: Dispatcher Key
