### ISSUE TITLE
Bug - Your Internet is Disconnected

### ISSUE THREAD

**Issue by ReMaKeRr02** [neon-nyan/Collapse#77] opened 2023-02-08 13:25 UTC
Hello. I am using the latest update, but for some reason IDK, Collapse Launcher keeps giving me an error of "Your Internet is Disconnected", while I am online. I'm using Windows 11 by the way.

Here's the error message:
`System.NullReferenceException: Object reference not set to an instance of an object.
   at Hi3Helper.Http.Http.InitializeMultiSession() in C:\myGit\Collapse-Legacy\Hi3Helper.Http\Class\Session\SessionManager.cs:line 188
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Hi3Helper.Http.Http.Download(String URL, String Output, Byte ConnectionSessions, Boolean Overwrite, CancellationToken ThreadToken) in C:\myGit\Collapse-Legacy\Hi3Helper.Http\HttpMulti.cs:line 54
   at CollapseLauncher.MainPage.DownloadBackgroundImage() in C:\myGit\Collapse-Legacy\CollapseLauncher\Classes\BackgroundManagement\BackgroundManagement.cs:line 378
   at CollapseLauncher.MainPage.FetchLauncherLocalizedResources() in C:\myGit\Collapse-Legacy\CollapseLauncher\Classes\BackgroundManagement\BackgroundManagement.cs:line 46
   at CollapseLauncher.MainPage.IsTryLoadGameRegionTaskFail(Task InnerTask, UInt32 Timeout) in C:\myGit\Collapse-Legacy\CollapseLauncher\Classes\RegionManagement\RegionManagement.cs:line 143`

Thanks for checking in from now.

**Comment by neon-nyan** [comment] 2023-02-08 13:28
Hi there,

Thank you for reporting in.
This is a known issue caused by a bug in the submodule. This bug exists in 1.0.55.6 and is fixed in the preview release.

For now, you can try to use the preview release and see if it fixes your problem.

**Comment by neon-nyan** [comment] 2023-03-05 11:50
Closing this issue for now as the fix will be shipped in the next stable release.

**Closed by neon-nyan** 2023-03-05 11:50 UTC
Labels: Bug, Area: Hi3Helper.Http
