### ISSUE TITLE
[Bug]: Collapse crashes with an NPE when it starts.

### ISSUE THREAD

**Issue by NishikiAsumi0** [neon-nyan/Collapse#253] opened 2023-08-28 05:12 UTC
### Affected Version

1.71.8

### Bug Behavior

the program crashes with an NPE when collapse tries to download the background image.

### Expected Behavior

the program starts correctly.

### Steps to reproduce

1. start the program and it crashes

### Screenshot(s)

![image](https://github.com/neon-nyan/Collapse/assets/58659973/eab36617-eb38-4930-a27b-69e7671a82ad)
![image](https://github.com/neon-nyan/Collapse/assets/58659973/7cabe7ae-f724-4bc6-aa36-24fa85eaa42d)

### Additional Information

[DxDiag.txt](https://github.com/neon-nyan/Collapse/files/12450433/DxDiag.txt)
it seems like that there is no log file in the default location :(
![20230828130858](https://github.com/neon-nyan/Collapse/assets/58659973/dae2255f-447a-4324-95b6-c8ff76b36779)

**Comment by muscularcandy67** [comment] 2023-08-28 05:17
Thank you for reporting the issue. When trying to reload a loading bar should appear, try to click on cancel as fast as you can and then try to switch to every other game/region to make sure the issue is localized on a single game/region or not

**Comment by bagusnl** [comment] 2023-08-28 05:40
After doing what @muscularcandy67 said, can you send the content of the stampv2.json inside Collapse's AppData _metadata folder?
To go to Collapse data folder, go to App Settings->Open App Data Folder

**Comment by bagusnl** [comment] 2023-08-28 06:05
As its the same error as #252 for the ease of communication we're gonna close this and move the discussion to that thread instead

**Closed by bagusnl** 2023-08-28 06:05 UTC
Labels: Needs Triaging
