### ISSUE TITLE
[Bug]: Can't read HSR's game settings correctly

### ISSUE THREAD

**Issue by LaoshuBaby** [neon-nyan/Collapse#173] opened 2023-06-15 21:41 UTC
### Affected Version

Collapse 1.70.8 Preview

### Bug Behavior

不能正确读取游戏中的图像设置（在启动器中显示的和游戏中设定的不一样）

In-game graphics settings not being read correctly (shown in launcher is different from in-game settings)

![图片](https://github.com/neon-nyan/Collapse/assets/42690037/e19e4ae6-3a54-425d-9a6a-911cdce1299a)
![图片](https://github.com/neon-nyan/Collapse/assets/42690037/86f5d444-a1df-467b-a1f9-5c80bb091547)

1.我开启了垂直同步，但启动器中并没有读取到。
2.我选择了游戏给出的1600x900，但启动器认为这是我自定义的分辨率而非下拉菜单中的预设。
~~3.我在启动器中更改自定义分辨率会造成所有设置全部失效~~

1. I turned on v-sync, but it was not read in the launcher.
2. I chose the 1600x900 given by the game, but the launcher thought it was my custom resolution instead of the preset in the drop-down menu.
~~3. If I change the custom resolution in the launcher, all settings will be invalid~~

（OK, custom resolution changes isn't a bug)

> Good implementation so far and seems have no issue at the moment besides that the Resolution options like "Custom Resolution" isn't working well because of the game forcing to allow only device-supported list of resolutions.  —— #129 

### Expected Behavior

启动器中的设置应能对应游戏中的设置，且能识别分辨率是否为预设。启动器中更改不应导致游戏中的设置全被重置为默认值。

（我一打开游戏发现突然变成全屏的时候人都傻了）

The settings in the launcher should correspond to the settings in the game and recognize whether the resolution is preset or not. Changes in the launcher should not cause all in-game settings to be reset to default.

(As soon as I opened the game, I was shocked when it suddenly became full screen)

### Steps to reproduce

1. 在启动器里设置
2. 打开游戏检查是否一致

1. Set in the launcher
2. Open the game to check whether it is consistent

### Related Issues

#123 
#129

**Comment by bagusnl** [comment] 2023-06-16 01:11
V-Sync toggle seems to be working just fine on my end. One single exception though, the game settings seem to be not refreshed every time the Game Settings open, rather every time the region is loaded (can confirmed the V-Sync toggle didn't refresh until I change region and get back to HSR:Glb). Can you confirm this behavior is your issue?

**Comment by bagusnl** [comment] 2023-06-16 22:42
> When disable **Full Screen**, the value of `Screenmanager Fullscreen mode_h3630240806` in registry is `3`, not `0`. Game window size will change uncontrollably if it is `0`.

I just noticed this behavior too, seems like when the value is 0 the window is fullscreen for 1 frame then immediately went back to windowed. Unsure why and I'd wait for neon's metadata dump so I can further analyze the options corresponding to which. I'll see what I can do to patch this issue in the meantime.

**Comment by bagusnl** [comment] 2023-06-18 04:35
All the settings should be reloaded now once it has a change either in-game or manually via regedit with commit https://github.com/neon-nyan/Collapse/commit/f7c5e78a9791f7bad074576186fa98c884054094

**Comment by Cryotechnic** [comment] 2023-06-21 20:56
Fixed in f7c5e78 & #168. Keeping this issue open for tracking until 1.70.X release. Thanks for your report!

**Closed** 2023-06-25 05:34 UTC
Labels: Fixed, Area: Preset Config, Area: UI/UX
