### ISSUE TITLE
A Major Bug on Genshin

### ISSUE THREAD

**Issue by tilsgee** [neon-nyan/Collapse#84] opened 2023-02-24 09:53 UTC
Launcher version: v1.0.69.2 Preview under Windows 11

in-game error code: 31-4302

Ordinary Log file:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Hi3Helper.Data.GenshinDispatchHelper.ParseGameResPkgProp(QueryProperty& ValProp) in C:\myGit\CollapseLauncher\Hi3Helper.Core\Classes\Data\Tools\GenshinDispatchHelper\GenshinDispatchHelper.cs:line 103
   at Hi3Helper.Data.GenshinDispatchHelper.LoadDispatch(Byte[] CustomDispatchData) in C:\myGit\CollapseLauncher\Hi3Helper.Core\Classes\Data\Tools\GenshinDispatchHelper\GenshinDispatchHelper.cs:line 83
   at CollapseLauncher.InstallManagement.InitializeNewGenshinDispatch() in C:\myGit\CollapseLauncher\CollapseLauncher\Classes\InstallManagement\InstallManagement.cs:line 839
   
Console Log file:
   [Erro]  Failed while loading the dispatcher! :(
System.NullReferenceException: Object reference not set to an instance of an object.
   at Hi3Helper.Data.GenshinDispatchHelper.ParseGameResPkgProp(QueryProperty& ValProp) in C:\myGit\CollapseLauncher\Hi3Helper.Core\Classes\Data\Tools\GenshinDispatchHelper\GenshinDispatchHelper.cs:line 103
   at Hi3Helper.Data.GenshinDispatchHelper.LoadDispatch(Byte[] CustomDispatchData) in C:\myGit\CollapseLauncher\Hi3Helper.Core\Classes\Data\Tools\GenshinDispatchHelper\GenshinDispatchHelper.cs:line 83
   at CollapseLauncher.InstallManagement.InitializeNewGenshinDispatch() in C:\myGit\CollapseLauncher\CollapseLauncher\Classes\InstallManagement\InstallManagement.cs:line 839
[Info]  data_versions (silence) path: https://autopatchhk.yuanshen.com/client_design_data/3.4_live/output_12901190_326dbbbf65/client_silence/General/AssetBundles/data_versions
[Info]  data_versions path: https://autopatchhk.yuanshen.com/client_design_data/3.4_live/output_13021296_8f79734b55/client/General/AssetBundles/data_versions
[Warn]  There's a problem while fetching the list of the persistent manifest via dispatcher. Skipping!
System.Threading.Tasks.TaskCanceledException: The operation was canceled.
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Hi3Helper.Http.Http.InitializeSingleSession(Nullable`1 OffsetStart, Nullable`1 OffsetEnd, Boolean IsFileMode, Stream _Stream, Boolean IgnoreOutStreamLength) in C:\myGit\CollapseLauncher\Hi3Helper.Http\Class\Session\SessionManager.cs:line 41
   at Hi3Helper.Http.Http.<>c__DisplayClass56_0.<Download>b__0() in C:\myGit\CollapseLauncher\Hi3Helper.Http\Http.cs:line 131
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Hi3Helper.Http.Http.Download(String URL, Stream Outstream, Nullable`1 OffsetStart, Nullable`1 OffsetEnd, CancellationToken ThreadToken, Boolean IgnoreOutStreamLength) in C:\myGit\CollapseLauncher\Hi3Helper.Http\Http.cs:line 130
   at CollapseLauncher.InstallManagement.BuildPersistentManifest(List`1 Entries, Dictionary`2 HashtableManifest) in C:\myGit\CollapseLauncher\CollapseLauncher\Classes\InstallManagement\InstallManagement.cs:line 896
   at CollapseLauncher.InstallManagement.PostInstallVerification(UIElement Content) in C:\myGit\CollapseLauncher\CollapseLauncher\Classes\InstallManagement\InstallManagement.cs:line 738

**Comment by neon-nyan** [comment] 2023-02-24 10:20
Wait, that's weird. How about in stable build? Does this reproduceable?
The maintenance for the next update hasn't been taken place, right?

**Comment by neon-nyan** [comment] 2023-02-25 02:37
Hi @tilsgee,

We've just added a commit for the fix and it will be included in the next preview release.

For now, you can use stable release while waiting for the fix to be applied in the next preview release

**Comment by neon-nyan** [comment] 2023-02-26 13:48
This issue will be closed since it's already fixed and will be shipped in the next version

**Closed by neon-nyan** 2023-02-26 13:48 UTC
Labels: Bug, Fixed, Game: Genshin Impact, Area: Dispatcher Key
