### ISSUE TITLE
Can't download star rail

### ISSUE THREAD

**Issue by futamiyarn** [neon-nyan/Collapse#154] opened 2023-05-28 19:12 UTC
When download star rail, show not responding
![image](https://github.com/neon-nyan/Collapse/assets/21020026/a2ed14a4-ce26-45f9-922d-06eeb149d41f)

**Comment by neon-nyan** [comment] 2023-05-29 02:52
Hi @yarndinasti

Thanks for reporting this.
This is a known issue on the latest version of stable releases and this was caused by a few changes being made recently.

A hotfix is currently underway and hopefully will be shipped as soon as we possibly can.

**Comment by bagusnl** [comment] 2023-06-04 17:03
Hi, I've made a debug build using latest commit that include the fix that you can test here:
https://www.mediafire.com/file/13h54rtrckdkmbe/Collapse-Debug_670b93d47783e2b409bdb2bf7bed2345fbd0c949_10.0.19041.0_Net7.0.7z/file
Please keep in mind that this debug build doesn't have any updater so make sure to use normal builds (pre/stable) after you've done with downloading the game. 

To use this build, just extract it and run CollapseLauncher.exe, all configs from normal build will be used.

Let us know if you have any difficulties or issues using this build.

**Comment by neon-nyan** [comment] 2023-06-06 05:31
Hi @yarndinasti,

This bug should've been fixed in the recent update. Please update your launcher to the latest version.

We are going to close this issue in 24 hours if you don't have any other issues.

**Closed** 2023-06-18 15:21 UTC
Labels: Bug, Fixed, Area: Preset Config, Game: Honkai Impact 3rd, Game: Honkai: Star Rail, Area: Runtime
