### ISSUE TITLE
[Bug]: Region Switch Lock After Switching to Another Region

### ISSUE THREAD

**Issue by pha1n0q** [neon-nyan/Collapse#273] opened 2023-09-25 02:11 UTC
### Affected Version

Collapse 1.71.11

### Bug Behavior

When you open the launcher, it opens to whatever region you had it open to before. After switching to a new region, it will not let you open the region that was first opened on app start. The only way of going back to the 'locked' region is by reopening the app.

### Expected Behavior

Collapse should not 'lock' the region that was originally launched when the launcher opened; it should let the user switch regions freely.

### Steps to reproduce

1. Open Collapse Launcher
2. Switch to a new region
3. Attempt to switch back to the region that was shown when Collapse opened
4. Get gatekept :)

### Screenshot(s)

Recording that demonstrates how the bug prevents the user from going back to the 'locked' region: https://youtu.be/6ZCpF-TrOV0

### Additional Information

Launcher console log: [log-2023-09-24-sta1.71.11-id1.log](https://github.com/neon-nyan/Collapse/files/12710415/log-2023-09-24-sta1.71.11-id1.log)

I did not encounter this issue in the previous major release (1.71.9).

**Comment by bagusnl** [comment] 2023-09-25 05:41
Thank you for letting us know about the bug!
I can confirm this bug only happening in stable. Will investigate further

**Comment by bagusnl** [comment] 2023-09-25 06:08
Fixed in https://github.com/neon-nyan/Collapse/commit/b9da055847054ce1257870e4e96117ca12612148
This caused by commit 68dad60 partially lost, most likely due to git merge error. We will include this on tonight hotfix. Sorry for the inconvenience

**Closed as completed** 2023-09-26 19:48 UTC
Labels: Bug, Area: UI/UX
